---
- name: Provision EC2 Instance for DC
  hosts: localhost 
  connection: local 
  gather_facts: false
  vars: 
    group_name: ad_server
    short_desc: ActiveDirectory
    server_env: prod 
    server_os: windows
    business_domain_name: "{{ survey_business_domain_name }}"
  roles:
    - aws-setup
    - aws-provision-windows 