--- 
- name: Setup Demo Environment
  hosts: localhost
  connection: local
  tasks:
    - name: import login credentials for Tower
      include_vars: "{{lookup('first_found', login_info)}}"
      vars:
        login_info:
          - 'private.yml'
          - 'login_info.yml'

    - name: Create Ansible Windows Ops demo Tower Project
      awx.awx.tower_project:
        name: Windows Ops
        state: present
        organization: Default 
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        tower_host: https://localhost
        tower_verify_ssl: false
        scm_type: git 
        scm_url: https://github.com/corumj/ansible-windows-demo.git
        scm_update_on_launch: yes 

    - name: Create AWS Credential 
      awx.awx.tower_credential:
        state: present
        name: AWS Console
        description: AWS Credential from saml 
        organization: Default 
        credential_type: Amazon Web Services
        inputs:
          username: "{{ AWS_ACCESS_KEY_ID }}"
          password: "{{ AWS_SECRET_ACCESS_KEY }}"
          security_token: "{{ AWS_SECURITY_TOKEN }}"
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        tower_host: https://localhost
        tower_verify_ssl: false

    - name: Create AWS Machine Credential 
      awx.awx.tower_credential:
        state: present 
        name: AWS Windows Machine 
        description: AWS Windows Machine Credential 
        organization: Default 
        credential_type: Machine 
        inputs:
          username: Administrator
          password: "{{ win_initial_password }}"
          become_method: runas 
          become_username: Administrator 
          become_password: "{{ win_initial_password }}"
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        tower_host: https://localhost
        tower_verify_ssl: false

    - name: Create AWS Inventory 
      awx.awx.tower_inventory: 
        name: AWS
        description: AWS Inventory 
        organization: Default 
        state: present 
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        tower_host: https://localhost
        tower_verify_ssl: false

    - name: Create AWS Inventory Source
      awx.awx.tower_inventory_source:
        state: present  
        name: AWS 
        description: AWS inventory source 
        inventory: AWS  
        credential: AWS Console  
        # instance_filters: "tag:app={{ app }}"
        overwrite: True  
        update_on_launch: True  
        source: ec2  
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        tower_host: https://localhost
        tower_verify_ssl: false

    - name: Create the Windows group 
      awx.awx.tower_group: 
        name: windows 
        inventory: AWS  
        variables:
          ansible_port: 5986
          ansible_connection: winrm
          ansible_winrm_server_cert_validation: ignore
        state: present 
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        tower_host: https://localhost
        tower_verify_ssl: false
        
    - name: Create provisioning template
      awx.awx.tower_job_template:
        name: "Provision EC2 Instance"
        job_type: "run"
        inventory: "AWS"
        project: "Windows Ops"
        playbook: "provision.yml"
        credentials: 
          - "AWS Console"
          - "Tower Credential"
        job_tags: "provision"
        state: "present"
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        tower_host: https://localhost
        tower_verify_ssl: false

    - name: Create deprovisioning template
      awx.awx.tower_job_template:
        name: "Deprovision EC2 Instance"
        job_type: "run"
        inventory: "AWS"
        project: "Windows Ops"
        playbook: "provision.yml"
        credentials: 
          - "AWS Console"
        job_tags: "deprovision"
        state: "present"
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        tower_host: https://localhost
        tower_verify_ssl: false

    - name: Create Windows Update job template
      awx.awx.tower_job_template:
        name: "Windows Updates"
        job_type: run
        inventory: AWS
        project: "Windows Ops"
        playbook: windows_updates.yml
        credentials:
          - "AWS Windows Machine"
        limit: "tag_app_{{ app }}"
        state: present
        tower_config_file: "~/.tower_cli.cfg"
        survey_enabled: yes
        survey_spec: "{{ lookup('file', 'windows_update_survey.json') }}"