---   
- name: Teardown demo 
  hosts: localhost
  connection: local 
  tasks:
    - name: import login credentials for Tower
      include_vars: "{{lookup('first_found', login_info)}}"
      vars:
        login_info:
          - 'private.yml'
          - 'login_info.yml'

    - name: Remove Ansible Git Ops demo Tower Project
      awx.awx.tower_project:
        name: Windows Ops
        state: absent
        organization: Default 
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        tower_host: https://localhost
        tower_verify_ssl: false
        scm_type: git 
        scm_url: https://github.com/corumj/ansible-gitops-demo.git
        scm_update_on_launch: yes 

    - name: Delete AWS Credential 
      awx.awx.tower_credential:
        state: absent
        name: AWS Console
        description: AWS Credential from saml 
        organization: Default 
        credential_type: Amazon Web Services
        inputs:
          username: "{{ AWS_ACCESS_KEY_ID }}"
          password: "{{ AWS_SECRET_ACCESS_KEY }}"
          security_token: "{{ AWS_SECURITY_TOKEN }}"
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        tower_host: https://localhost
        tower_verify_ssl: false

    - name: Delete AWS Keypair 
      amazon.aws.ec2_key: 
        name: "{{ aws_key_name }}"
        state: absent
        region: "{{ region }}"
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        security_token: "{{ AWS_SECURITY_TOKEN }}"
      register: ssh_key

    - name: Delete AWS Machine Credential 
      awx.awx.tower_credential:
        state: absent 
        name: AWS Machine 
        description: AWS Machine Credential 
        organization: Default 
        credential_type: Machine 
        inputs:
          username: ec2-user 
          ssh_key_data: "{{ ssh_key }}"
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        tower_host: https://localhost
        tower_verify_ssl: false

    - name: Delete AWS Inventory 
      awx.awx.tower_inventory: 
        name: AWS
        description: AWS Inventory 
        organization: Default 
        state: absent 
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        tower_host: https://localhost
        tower_verify_ssl: false

    - name: Delete provisioning template
      awx.awx.tower_job_template:
        name: "Provision EC2 Instance"
        job_type: "run"
        inventory: "AWS"
        project: "Windows Ops"
        playbook: "provision.yml"
        credentials: 
          - "AWS Console"
        job_tags: "provision"
        state: absent
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        tower_host: https://localhost
        tower_verify_ssl: false

    - name: Delete deprovisioning template
      awx.awx.tower_job_template:
        name: "Deprovision EC2 Instance"
        job_type: "run"
        inventory: "AWS"
        project: "Windows Ops"
        playbook: "provision.yml"
        credentials: 
          - "AWS Console"
        job_tags: "deprovision"
        state: absent
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        tower_host: https://localhost
        tower_verify_ssl: false

    - name: Remove EC2 Instance 
      community.aws.ec2_instance:
        state: absent
        region: "{{ region }}"
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        security_token: "{{ AWS_SECURITY_TOKEN }}"
        filters:
          "tag:app": "{{ app }}"

    - name: Remove security group 
      amazon.aws.ec2_group: 
        name: "{{ id }}-sec-group"
        description: Inbound WinRM and RDP 
        region: "{{ region }}"
        state: absent