---
- name: Deprovision Demo
  hosts: localhost
  connection: local
  vars:
    business_domain_name: "{{ hostvars[groups['ad_server'][0]]['tags']['business_domain_name'] }}"
  gather_facts: false
  roles:
    - aws-deprovision 