---
- name: Setup Windows demo 
  hosts: localhost
  connection: local 
  vars:
    win_initial_password: "{{ survey_win_init_password }}"
    win_initial_password_verify: "{{ survey_win_init_password_verify }}"
    valid_password: "{{ win_initial_password | regex_search('^(?=.*[\d])(?=.*[A-Z])(?=.*[a-z])(?=.*[@#$])[\w\d@#$]{6,12}$') }}"
  tasks:
    - name: Fail if passwords don't match
      fail:
        msg: "Entered passwords do not match, please try again."
      when: 
        - win_initial_password != win_initial_password_verify
        - valid_password