---
- name: Setup Windows demo 
  hosts: localhost
  connection: local 
  vars:
    win_initial_password: "{{ survey_win_init_password }}"
    win_initial_password_verify: "{{ survey_win_init_password_verify }}"
  tasks:
    - name: Fail if passwords don't match
      fail:
        msg: "Entered passwords do not match, please try again."
      when: 
        - win_initial_password != win_initial_password_verify
        - "{{ win_initial_password | regex_search('(?=^[A-Za-z\d!@#\$%\^&\*\(\)_\+=]{8,20}$)((?=.*\d)(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[!@#\$%\^&\*\(\)_\+=])(?=.*[a-z])|(?=.*[!@#\$%\^&\*\(\)_\+=])(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[A-Z])(?=.*[!@#\$%\^&\*\(\)_\+=]))^.*', '\\1') }}"