- name: Retrieve AWS connection info for instance
  hosts: localhost 
  connection: local
  tasks:
    # since we only have the instance name we need to lookup the ip address
    # since that's what is used in Tower for the name (probably can change that)
    - name: Retrieve Instance Info
      community.aws.ec2_instance_info:
        region: "{{ region }}"
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        filters:
          "tag:Name": "{{ instance_name }}"
          instance-state-name: ["running"]
      register: ec2_instance 

    - name: Promote to domain membership
      include_role:
        name: join-domain 
        apply:
          delegate_to: "{{ ec2_instance.instances[0].public_ip_address }}"
          run_once: true

    - name: Add server name to DNS record 
      community.windows.win_dns_record:
        name: "{{ instance_name | regex_search('-([^-]+)-', '\\1') }}.demo.lab"
        type: "A"
        value: "{{ ec2_instance.instances[0].public_ip_address }}"
        zone: "demo.lab"
      delegate_to: "{{ hostvars[groups['ad_server'][0]]['ec2_ip_address'] }}"
    