- name: Retrieve AWS connection info for instance
  hosts: localhost 
  connection: local 
  tasks:
    - name: Retrieve Instance Info
      community.aws.ec2_instance_info:
        region: "{{ region }}"
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        filters:
          "tag:Name": "{{ instance_name }}"
          instance-state-name: ["running"]
      register: ec2_instance 

    - set_fact:
        ec2: ec2_instance

- name: debug 
  hosts: localhost 
  connection: local 
  tasks:
    - name: debug 
      debug:
        var: ec2 

    - name: debug try to get ip 
      debug:
        msg: "{{ ec2.instances[0].public_ip_address }}"

# - name: Join instance to domain 
#   hosts: "{{ ec2_instance.instances[0].public_ip_address }}"
#   roles:
#     - join-domain
