---
- name: Provision a Windows Instance 
  hosts: localhost 
  connection: local 
  vars:
    function: "{{ serverFunction }}"
    ec2_instance_name: "{{ instance_name }}"
  roles:
    - aws-provision