--- 
- name: Update deprovisioning list
  hosts: localhost
  connection: local
  tasks:
    - name: gather list of servers available for deprovisioning 
      community.aws.ec2_instance_info:
        region: "{{ region }}"
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        filters:
          "tag:app": "{{ app }}"
          instance-state-name: ["pending", "running"]
      register: ec2_instances 

    - name: Create a temporary place for survey template 
      tempfile:
        state: directory
        suffix: template 
      register: tmp 

    - name: Create survey spec file 
      template:
        src: deprovision.json.j2
        dest: "{{ tmp.path }}/deprovision.json"

    - name: Update deprovision single EC2 Instance
      awx.awx.tower_job_template:
        name: "Deprovision Specific EC2 Instance"
        job_type: "run"
        inventory: "AWS"
        project: "Windows Ops"
        playbook: "deprovision.yml"
        job_tags: "single"
        credentials: 
          - "AWS Console"
        survey_enabled: yes 
        survey_spec: "{{ lookup('file', '{{ tmp.path }}/deprovision.json') }}"
        state: "present"
        tower_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
        tower_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
        tower_host: https://localhost
        tower_verify_ssl: false