- name: Provision EC2 Instance for DC
  hosts: localhost 
  connection: local 
  vars: 
    function: ad_server
    ec2_instance_name: ActiveDirectory
  roles:
    - aws-provision 

- name: Create Domain Controller and Domain
  hosts: ad_server
  roles:
    - windows-ad-controller
