- name: Provision EC2 Instance for DC
  hosts: localhost 
  connection: local 
  gather_facts: false
  vars: 
    function: ad_server
    ec2_instance_name: ActiveDirectory
  roles:
    - aws-setup
    - aws-provision 

- name: Refresh inventory 
  hosts: localhost 
  connection: local 
  tasks:
    - meta: refresh_inventory
    
- name: Create Domain Controller and Domain
  hosts: ad_server
  gather_facts: false
  roles:
    - windows-ad-controller
