- name: create a VPC 
  amazon.aws.ec2_vpc_net:
    state: present
    name: "{{ id }}-vpc"
    cidr_block: 10.0.0.0/16
    tenancy: default
    tags:
      app: "{{ app }}"
      business_domain_name: "{{ survey_business_domain_name | default('demo') }}"
    region: "{{ region }}"
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
  register: demo_vpc

- name: Create Internet Gateway for VPC  
  community.aws.ec2_vpc_igw:
    state: present
    vpc_id: "{{ demo_vpc.vpc.id }}"
    tags:
      Name: "{{ id }}-vpc-igw"
      app: "{{ app }}"
      business_domain_name: "{{ survey_business_domain_name | default('demo') }}"
    region: "{{ region }}"
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
  register: gateway

- name: Create security group internal
  amazon.aws.ec2_group: 
    state: present
    name: "{{ id }}-sec-group"
    description: Inbound WinRM and RDP 
    rules:
      - proto: tcp 
        ports:
          - 80 
          - 5986 # WinRM
          - 3389 # RDP
          - 389 # LDAP (external to hook up with Tower)
          - 3268 # LDAP GC (external to hook up with Tower)
        cidr_ip: 0.0.0.0/0
      - proto: udp 
        ports:
          - 389 # LDAP (external to hook up with Tower)
        cidr_ip: 0.0.0.0/0
      - proto: icmp
        to_port: -1
        from_port: -1
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        ports: 
          - 80
          - 5986 # WinRM
          - 3389 # RDP
          - 53 # DNS
          - 88 # Kerberos Authentication
          - 135 # RPC
          - 139 # Netlogon 
          - 389 # LDAP 
          - 445 # SMB
          - 464 # Kerberos Authentication
          - 636 # LDAPS (LDAP over TLS)
          - 873 # Rsync 
          - 3268-3269 # Global Catalog 
          - 1024-65535 # Ephemeral RPC ports
        cidr_ip: 10.0.0.0/16
      - proto: udp 
        ports: 
          - 53 # DNS
          - 88 # Kerberos Authentication
          - 123 # NTP
          - 137-138 # Netlogon 
          - 389 # LDAP 
          - 445 # SMB
          - 464 # Kerberos Authentication
          - 1024-65535 # Ephemeral RPC ports
        cidr_ip: 10.0.0.0/16
    rules_egress:
      - proto: -1 
        cidr_ip: 0.0.0.0/0
    vpc_id: "{{ demo_vpc.vpc.id }}"
    tags:
      Name: "{{ id }}-sec-group"
      app: "{{ app }}"
      business_domain_name: "{{ survey_business_domain_name | default('demo') }}"
    region: "{{ region }}"
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
  register: internal_sg

- name: Create a subnet on the VPC for our apps
  amazon.aws.ec2_vpc_subnet:
    state: present
    vpc_id: "{{ demo_vpc.vpc.id }}"
    cidr: 10.0.0.0/16
    map_public: yes
    tags:
      Name: "{{ id }}-subnet"
      app: "{{ app }}"
      business_domain_name: "{{ survey_business_domain_name | default('demo') }}"
    region: "{{ region }}"
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
  register: demo_subnet

- name: Create a subnet route table 
  community.aws.ec2_vpc_route_table:
    state: present 
    vpc_id: "{{ demo_vpc.vpc.id }}"
    subnets:
      - "{{ demo_subnet.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0 
        gateway_id: "{{ gateway.gateway_id }}"
    tags: 
      Name: "{{ id }}-vpc-rtbl"
      app: "{{ app }}"
      business_domain_name: "{{ survey_business_domain_name | default('demo') }}"
    region: "{{ region }}"
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    