---
# defaults file for windows-ad-controller
dns_domain_name: "demo.local"
domain_admin_password: "Ansible!!1"

# Users and Password to Create
users_password: "Ansible!1"        # MUST FOLLOW WINDOWS AD PASSWORD RULES
users:
  - "{{ name }}"  # will pull your name from group_vars/all.yml for consistency

# Details for reverse DNS lookup
ptr_zone_name: "172.31.0.in-addr.arpa"
ptr_zone_cidr: "172.31.0.0/16"
