---
# - name: print hostvars 
#   debug:
#     var: hostvars[groups['tag_function_ad_server'][0]]['ec2_private_ip_address']

- name: Disable firewall for domain, public and private profiles 
  win_firewall:
    state: disabled 
    profiles:
      - Domain 
      - Private 
      - Public 
  tags: disable_firewall 

- name: configure DNS Client 
  ansible.windows.win_dns_client:
    adapter_names: "*"
    ipv4_addresses:
    - "{{ hostvars[groups['tag_function_ad_server'][0]]['ec2_private_ip_address'] }}"
  register: joined

- pause:
    minutes: 1
  when: joined.changed

- name: Add Windows Server to the Domain
  ansible.windows.win_domain_membership:
    dns_domain_name: "{{ domain_name }}"
    domain_admin_user: "admin@{{ domain_name }}"
    domain_admin_password: "{{ win_initial_password }}"
    domain_ou_path: "OU=Servers,OU=Ansible,DC=demo,DC=lab"
    state: domain
  register: domain_state

- name: Reboot Server if required
  ansible.windows.win_reboot:
  ignore_errors: true
  when: domain_state.reboot_required

