---
- name: Create Setup AD Controller Template
  awx.awx.tower_job_template:
    name: "2. Setup AD Controller (will auto run after creating business)"
    job_type: "run"
    inventory: "AWS"
    project: "Windows Ops"
    playbook: "ad-controller-setup.yml"
    credentials: 
      - "AWS Windows Machine"
    state: "present"
    tower_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
    tower_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    tower_host: https://localhost
    tower_verify_ssl: false

- name: Create Provisioning Template
  awx.awx.tower_job_template:
    name: "3. Simple Self Service Provisioning"
    job_type: "run"
    inventory: "AWS"
    project: "Windows Ops"
    playbook: "provision.yml"
    credentials: 
      - "AWS Console"
      - "Tower Credential"
    state: "present"
    survey_enabled: yes 
    survey_spec: "{{ lookup('file', 'files/provision-survey.json') }}"
    tower_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
    tower_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    tower_host: https://localhost
    tower_verify_ssl: false

- name: Create deprovisioning Template
  awx.awx.tower_job_template:
    name: "4. Deprovision Demo"
    job_type: "run"
    inventory: "AWS"
    project: "Windows Ops"
    playbook: "deprovision.yml"
    credentials: 
      - "AWS Console"
      - "Tower Credential"
    state: "present"
    tower_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
    tower_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    tower_host: https://localhost
    tower_verify_ssl: false