---
- name: Create Setup AD Controller Template
  awx.awx.tower_job_template:
    name: "2. Setup AD Controller (will auto run after creating business)"
    job_type: "run"
    inventory: "AWS"
    project: "Windows Ops"
    playbook: "ad-controller-setup.yml"
    credentials: 
      - "AWS Windows Machine"
    state: "present"
    tower_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
    tower_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    tower_host: https://localhost
    tower_verify_ssl: false