---
- name: Remove Setup AD Controller Template
  awx.awx.tower_job_template:
    name: "2. Setup AD Controller (will auto run after creating business)"
    job_type: "run"
    inventory: "AWS"
    project: "Windows Ops"
    playbook: "ad-controller-setup.yml"
    credentials: 
      - "AWS Windows Machine"
    state: "absent"
    tower_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
    tower_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    tower_host: https://localhost
    tower_verify_ssl: false

- name: Remove Provisioning Template
  awx.awx.tower_job_template:
    name: "3. Simple Self Service Provisioning"
    job_type: "run"
    inventory: "AWS"
    project: "Windows Ops"
    playbook: "provision.yml"
    credentials: 
      - "AWS Console"
      - "Tower Credential"
    state: "absent"
    survey_enabled: yes 
    survey_spec: "{{ lookup('file', 'files/provision-survey.json') }}"
    tower_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
    tower_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    tower_host: https://localhost
    tower_verify_ssl: false

- name: Remove deprovisioning Template
  awx.awx.tower_job_template:
    name: "4. Deprovision Demo"
    job_type: "run"
    inventory: "AWS"
    project: "Windows Ops"
    playbook: "deprovision.yml"
    credentials: 
      - "AWS Console"
      - "Tower Credential"
    state: "absent"
    tower_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
    tower_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    tower_host: https://localhost
    tower_verify_ssl: false

- name: Remove business domain group in Tower
  awx.awx.tower_group: 
    name: "{{ business_domain_name }}" 
    inventory: AWS  
    hosts:
      - "{{ ad.instances[0].public_ip_address }}"  
    variables:
      business_domain_name: "{{ survey_business_domain_name }}"   
      win_initial_password: "{{ survey_win_initial_password }}"
    state: absent 
    tower_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
    tower_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    tower_host: https://localhost
    tower_verify_ssl: false

- name: Remove AWS Machine Credential 
  awx.awx.tower_credential:
    state: absent 
    name: AWS Windows Machine 
    description: AWS Windows Machine Credential 
    organization: Default 
    credential_type: Machine 
    # inputs:
    #   username: Administrator
    #   password: "{{ win_initial_password }}"
    #   become_method: runas 
    #   become_username: Administrator 
    #   become_password: "{{ win_initial_password }}"
    tower_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
    tower_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    tower_host: https://localhost
    tower_verify_ssl: false

- name: remove ad_server group 
  awx.awx.tower_group: 
    name: ad_server
    inventory: AWS  
    # hosts:
    #   - "{{ ad.instances[0].public_ip_address }}"  
    # variables:
    #   business_domain_name: "{{ survey_business_domain_name }}"   
    #   win_initial_password: "{{ survey_win_initial_password }}"
    state: absent 
    tower_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
    tower_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    tower_host: https://localhost
    tower_verify_ssl: false