---

- name: Set upstream DNS server 
  ansible.windows.win_dns_client:
    adapter_names: '*'
    ipv4_addresses:
      - '{{ upstream_dns_1 }}'
      - '{{ upstream_dns_2 }}'

- name: Stop the time service
  win_service:
    name: w32time
    state: stopped 

- name: Set NTP Servers 
  win_shell: 'w32tm /config /syncfromflags:manual /manualpeerlist:"{{ntp_servers}}"'

- name: Start the time service 
  win_service:
    name: w32time 
    state: started 